name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upload Chrome version as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Chrome
          path: |
            **/*
            !.git/**/*
            !.github/**/*
            !.*

      - name: Edit manifest for Firefox
        run: |
          cp manifest.json manifest_firefox.json
          jq '.background = {scripts: ["background.js"]} | del(.background.service_worker)' manifest_firefox.json > tmp.json && mv tmp.json manifest_firefox.json
          mv manifest_firefox.json manifest.json

      - name: Upload Firefox version
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Firefox
          path: |
            **/*
            !.git/**/*
            !.github/**/*
            !.*

      - name: End
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          echo "# 🚀 SaveYourTime v$VERSION" >> $GITHUB_STEP_SUMMARY
